version: '3'
services:
  postgres:
    build:
      context: ./docker
      dockerfile: Dockerfile_Postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra:
    build:
      context: ./docker
      dockerfile: Dockerfile_Cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES;'"]
      interval: 10s
      timeout: 5s
      retries: 5